# Generated by Django 4.2.13 on 2024-05-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ManyToManyField(blank=True, null=True, to='server.ingredient'),
        ),
    ]
