# Generated by Django 4.2.13 on 2024-05-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
    ]
